services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      slither:
        condition: service_started
      postgres:
        condition: service_started
      redis:
        condition: service_started
    environment:
      # Server
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_ENV=${SERVER_ENV}

      # Database
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=${DB_SSL_MODE}

      # Redis
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}

      # Slither
      - SLITHER_CONTAINER_NAME=slither
      - WORKSPACE_PATH=/workspace
    networks:
      - app-network
      - slither-network
    volumes:
      - shared-workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  slither:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.slither
    container_name: slither
    networks:
      - slither-network
    volumes:
      - shared-workspace:/workspace
    command: tail -f /dev/null
    environment:
      - SOLC_VERSION=0.8.20
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "which", "slither"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
  slither-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  shared-workspace:
