basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for Slyther Go Backend.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Slyther Go Backend API
  version: "1.0"
paths:
  /contracts/{address}:
    get:
      consumes:
      - application/json
      description: Get a cached smart contract from the database by its address and
        network
      parameters:
      - description: Contract Address
        in: path
        name: address
        required: true
        type: string
      - default: ethereum
        description: Network Name
        in: query
        name: network
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get contract from database
      tags:
      - contracts
  /contracts/{address}/source-code:
    get:
      consumes:
      - application/json
      description: Get the source code of a smart contract from Etherscan by its address
        and save it to the database
      parameters:
      - description: Contract Address
        in: path
        name: address
        required: true
        type: string
      - default: ethereum
        description: Network Name
        in: query
        name: network
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get contract source code
      tags:
      - contracts
    post:
      consumes:
      - application/json
      description: Forces a refresh of the source code of a smart contract from Etherscan
        by its address
      parameters:
      - description: Contract Address
        in: path
        name: address
        required: true
        type: string
      - default: ethereum
        description: Network Name
        in: query
        name: network
        type: string
      produces:
      - application/json
      responses: {}
      summary: Refresh contract source code
      tags:
      - contracts
schemes:
- http
- https
swagger: "2.0"
